<a href="https://colab.research.google.com/github/yashkhetpal/dsv-practice/blob/main/DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

In [ ]:
#Now we'll learn DataFrames

#Let's get some data to play with. How about the NFL?
import webbrowser
website = 'http://en.wikipedia.org/wiki/NFL_win-loss_records'
webbrowser.open(website)

True

In [ ]:
#Copy and read to get data
nfl_frame = pd.read_clipboard()

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

In [ ]:
#Show
nfl_frame

NameError: name 'nfl_frame' is not defined

In [ ]:
nfl_frame=pd.read_csv("nfl_data.csv")

In [ ]:
nfl_frame

,Rank,Team,GP,Won,Lost,Tied[b],Pct.,First NFL season,Division
0,32,Tampa Bay Buccaneers,793,326,466,1,0.412,1976,NFC South
1,31,Arizona Cardinals,"1,463",596,826,41 (6),0.419,1920,NFC West
2,30,Jacksonville Jaguars,501,215,286,0,0.429,1995,AFC South
3,29,New York Jets,"1,017",436,573,8 (2),0.432,1960,AFC East
4,28,Atlanta Falcons,933,406,521,6 (2),0.438,1966,NFC South
5,27,Houston Texans,389,174,214,1,0.449,2002,AFC South
6,26,Carolina Panthers,501,227,273,1,0.454,1995,NFC South
7,25,Cincinnati Bengals,904,409,490,5 (4),0.455,1968,AFC North
8,24,Detroit Lions,"1,366",615,717,34 (5),0.462,1930,NFC North
9,23,New Orleans Saints,919,423,491,5 (1),0.463,1967,NFC South
10,22,Tennessee Titans,"1,017",482,529,6 (0),0.477,1960,AFC South
11,21,Buffalo Bills,"1,016",498,510,8 (1),0.494,1960,AFC East
12,20,Washington Commanders,"1,335",646,660,29 (3),0.495,1932,NFC East
13,19,Los Angeles Chargers,"1,017",505,501,11 (2),0.502,1960,AFC West
14,18,Philadelphia Eagles,"1,321",649,645,27 (7),0.502,1933,NFC East
15,17,Cleveland Browns[c][e],"1,141",567,560,14 (4),0.503,1946,AFC North
16,16,Las Vegas Raiders,"1,017",512,494,11 (2),0.509,1960,AFC West
17,15,Los Angeles Rams,"1,268",636,611,21 (3),0.510,1937,NFC West
18,14,New York Giants,"1,438",728,676,34 (4),0.518,1925,NFC East
19,13,Indianapolis Colts[d],"1,099",572,519,8 (2),0.524,1953,AFC South
20,12,Seattle Seahawks,793,416,376,1,0.525,1976,NFC West
21,11,Denver Broncos,"1,017",532,475,10 (4),0.528,1960,AFC West
22,10,Pittsburgh Steelers,"1,305",691,592,22 (4),0.538,1933,AFC North
23,9,San Francisco 49ers[c],"1,189",642,531,16 (3),0.547,1946,NFC West
24,8,Miami Dolphins,933,511,418,4 (1),0.550,1966,AFC East
25,7,Minnesota Vikings,"1,003",546,446,11 (4),0.550,1961,NFC North
26,6,Kansas City Chiefs,"1,017",553,452,12 (4),0.550,1960,AFC West
27,5,Chicago Bears,"1,503",809,652,42 (1),0.554,1920,NFC North
28,4,New England Patriots,"1,017",559,449,9 (0),0.555,1960,AFC East
29,3,Baltimore Ravens,485,276,208,1,0.570,1996,AFC North
30,2,Dallas Cowboys,"1,015",576,432,7 (1),0.571,1960,NFC East
31,1,Green Bay Packers,"1,469",819,611,39 (8),0.572,1921,NFC North

In [ ]:
# We can grab the oclumn names with .columns
nfl_frame.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8'],
      dtype='object')

In [ ]:
#Lets see some specific data columns
DataFrame(nfl_frame,columns=['Team','First Season','Total Games'])

    Team  First Season  Total Games
0    NaN           NaN          NaN
1    NaN           NaN          NaN
2    NaN           NaN          NaN
3    NaN           NaN          NaN
4    NaN           NaN          NaN
5    NaN           NaN          NaN
6    NaN           NaN          NaN
7    NaN           NaN          NaN
8    NaN           NaN          NaN
9    NaN           NaN          NaN
10   NaN           NaN          NaN
11   NaN           NaN          NaN
12   NaN           NaN          NaN
13   NaN           NaN          NaN
14   NaN           NaN          NaN
15   NaN           NaN          NaN
16   NaN           NaN          NaN
17   NaN           NaN          NaN
18   NaN           NaN          NaN
19   NaN           NaN          NaN
20   NaN           NaN          NaN
21   NaN           NaN          NaN
22   NaN           NaN          NaN
23   NaN           NaN          NaN
24   NaN           NaN          NaN
25   NaN           NaN          NaN
26   NaN           NaN          NaN
27   NaN           NaN          NaN
28   NaN           NaN          NaN
29   NaN           NaN          NaN
30   NaN           NaN          NaN
31   NaN           NaN          NaN
32   NaN           NaN          NaN

In [ ]:
#What happens if we ask for a column that doesn't exist?
DataFrame(nfl_frame,columns=['Team','First Season','Total Games','Stadium'])

                Team  First Season  Total Games  Stadium
0     Dallas Cowboys          1960          894        0
1      Chicago Bears          1920         1357        1
2  Green Bay Packers          1921         1339        2
3     Miami Dolphins          1966          792        3
4   Baltimore Ravens          1996          326        4

In [ ]:
# Call columns
nfl_frame.columns

Index([u'Rank', u'Team', u'Won', u'Lost', u'Tied*', u'Pct.', u'First Season', u'Total Games', u'Conference', u'Stadium'], dtype='object')

In [ ]:
#We can retrieve individual columns
nfl_frame.Team

0       Dallas Cowboys
1        Chicago Bears
2    Green Bay Packers
3       Miami Dolphins
4     Baltimore Ravens
Name: Team, dtype: object

In [ ]:
nfl_frame.Total_Games

NameError: name 'nfl_frame' is not defined

In [ ]:
# Or try this method for multiple word columns
nfl_frame['Total Games']

0     894
1    1357
2    1339
3     792
4     326
Name: Total Games, dtype: int64

In [ ]:
#We can retrieve rows through indexing
nfl_frame.ix[3]

Rank                         4
Team            Miami Dolphins
Won                        443
Lost                       345
Tied*                        4
Pct.                     0.562
First Season              1966
Total Games                792
Conference            AFC East
Name: 3, dtype: object

In [ ]:
#We can also assign value sto entire columns
nfl_frame['Stadium']="Levi's Stadium" #Careful with the ' here

In [ ]:
nfl_frame

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference,Stadium
0,1,Dallas Cowboys,510,378,6,0.574,1960,894,NFC East,Levi's Stadium
1,2,Chicago Bears,752,563,42,0.570,1920,1357,NFC North,Levi's Stadium
2,3,Green Bay Packers,741,561,37,0.567,1921,1339,NFC North,Levi's Stadium
3,4,Miami Dolphins,443,345,4,0.562,1966,792,AFC East,Levi's Stadium
4,5,Baltimore Ravens,182,143,1,0.560,1996,326,AFC North,Levi's Stadium
5,6,San Francisco 49ers,545,444,14,0.550,1950,1003,NFC West,Levi's Stadium

In [ ]:
#Putting numbers for stadiums
nfl_frame["Stadium"] = np.arange(5)

#Show
nfl_frame

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference,Stadium
0,1,Dallas Cowboys,510,378,6,0.574,1960,894,NFC East,0
1,2,Chicago Bears,752,563,42,0.570,1920,1357,NFC North,1
2,3,Green Bay Packers,741,561,37,0.567,1921,1339,NFC North,2
3,4,Miami Dolphins,443,345,4,0.562,1966,792,AFC East,3
4,5,Baltimore Ravens,182,143,1,0.560,1996,326,AFC North,4

In [ ]:
# Call columns
nfl_frame.columns

Index([u'Rank', u'Team', u'Won', u'Lost', u'Tied*', u'Pct.', u'First Season', u'Total Games', u'Conference', u'Stadium'], dtype='object')

In [ ]:
#Adding a Series to a DataFrame
stadiums = Series(["Levi's Stadium","AT&T Stadium"],index=[4,0])

In [ ]:
#Now input into the nfl DataFrame
nfl_frame['Stadium']=stadiums

#Show
nfl_frame

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference,Stadium
0,1,Dallas Cowboys,510,378,6,0.574,1960,894,NFC East,AT&T Stadium
1,2,Chicago Bears,752,563,42,0.570,1920,1357,NFC North,NaN
2,3,Green Bay Packers,741,561,37,0.567,1921,1339,NFC North,NaN
3,4,Miami Dolphins,443,345,4,0.562,1966,792,AFC East,NaN
4,5,Baltimore Ravens,182,143,1,0.560,1996,326,AFC North,Levi's Stadium

In [ ]:
#We can also delete columns
del nfl_frame['Stadium']

nfl_frame

,Rank,Team,Won,Lost,Tied*,Pct.,First Season,Total Games,Conference
0,1,Dallas Cowboys,510,378,6,0.574,1960,894,NFC East
1,2,Chicago Bears,752,563,42,0.570,1920,1357,NFC North
2,3,Green Bay Packers,741,561,37,0.567,1921,1339,NFC North
3,4,Miami Dolphins,443,345,4,0.562,1966,792,AFC East
4,5,Baltimore Ravens,182,143,1,0.560,1996,326,AFC North

In [ ]:
#DataFrames can be constructed many ways. Another way is from a dictionary of equal length lists
data = {'City':['SF','LA','NYC'],
        'Population':[837000,3880000,8400000]}

city_frame = DataFrame(data)

#Show
city_frame

  City  Population
0   SF      837000
1   LA     3880000
2  NYC     8400000

In [ ]:
#For full list of ways to create DataFrames from various sources go to teh documentation for pandas:
website = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.html'
webbrowser.open(website)

True